### ISSUE TITLE
OneDrive error

### ISSUE THREAD

**Issue by clintonjwang** [POSTECH-CVLab/PeRFception#17]
Running
`python3 utils/download_perf.py --dataset co3d --outdir data/co3d/`
creates txt files with error:
```
Sorry, there was a problem downloading some files from OneDrive. Please try again.

OneDrive_1 - https://onedrive.live.com/?id=60A1A318FA7A3606%211420&action=Download&authKey=!ACaUbVBSIuDvCrI
```

**Comment by jeongyw12382** [comment]
Due to frequently observed connection errors, we have moved our data from OneDrive to HuggingFace. 
We recommend using the script here: 
https://github.com/POSTECH-CVLab/PeRFception#downloading-perfception-datastes-co3d-link1-co3d-link2-co3d-link3-scannet

We will soon remove the code that downloads data from OneDrive.

**Comment by jeongyw12382** [comment]
Please reopen the issue if you have any further problems regarding this issue.
