### ISSUE TITLE
Downloading specific categories and sequences

### ISSUE THREAD

**Issue by AlonMendelson** [POSTECH-CVLab/PeRFception#9]
Thanks for this great dataset. this is really impressive.
I wondered if there is a way to download the representations for specific co3d sequences from specific categories.
does the chunks have anything to do with this?

**Comment by jeongyw12382** [comment]
Glad to hear that our paper touched you. 
One of the easiest ways to download a specific sequence is to use GUI Onedrive to download the dataset. 

But, we are currently searching for the way to automatically download specific scene number in CLI. 
This is quite challenging since OneDrive links are encoded with a complex function.
 
If we found the way, we could also implement category-wise downloading scripts. We will let you know ASAP. 

Sorry for the inconvenience.

**Comment by jeongyw12382** [comment]
We have decided to additionally upload the dataset into HuggingFace. We'll soon let you know the way to download our dataset. Thanks.

**Comment by AlonMendelson** [comment]
Thanks a lot for your prompt response and willingness to help. This is much appreciated

**Comment by jeongyw12382** [comment]
We are currently having troubles regarding uploading on HuggingFace. We'll soon let you know how to easily access the data. Sorry for being late.

**Comment by jeongyw12382** [comment]
Hi. We have just added a new way to download whole or partial dataset from HuggingFace. We are pretty sure that this manual can help you. If you want to download specific categories, we recommend to put whole sequences from the given manual. 

https://github.com/POSTECH-CVLab/PeRFception#downloading-perfception-datastes-huggingface---recommended-link1-link2-link3

**Comment by jeongyw12382** [comment]
Closing the issue after adding a manual for downloading partial sequences.
